version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}
  a_socials_node_modules:

services:
  database:
    container_name: dev_andela_social_db
    build:
      context: ../../docker/database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - "8092:5432"

  server:
    container_name: dev_andela_social_server
    env_file:
      - ./dev.env
    build:
      context: ../../server
      dockerfile: ../docker/server/Dockerfile
    depends_on:
      - database
    ports:
      - "8000:8000"

  client:
    container_name: dev_andela_social_client
    build:
      context: ../../client
      dockerfile: ../docker/dev/client/Dockerfile
    env_file:
      - ./dev.env
    depends_on:
      - server
    ports:
      - "9000:9000"
    volumes:
      - ../../client:/andela_social
      - a_socials_node_modules:/andela_social/node_modules
