# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171121_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='slack_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
