# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20171207_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndelaUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=60, unique=True)),
                ('user_picture', models.TextField()),
                ('slack_name', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='attend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AndelaUserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AndelaUserProfile'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AndelaUserProfile'),
        ),
        migrations.DeleteModel(
            name='GoogleUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
