# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180710_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
