# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models
from oauth2client.contrib.django_util.models import CredentialsField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='andelauserprofile',
            name='credential',
            field=CredentialsField(null=True),
        ),
        migrations.AddField(
            model_name='andelauserprofile',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
