# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-26 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andelauserprofile',
            old_name='slack_name',
            new_name='slack_id',
        ),
    ]
