# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180731_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_category_action', models.CharField(choices=[('CREATE', 'CREATE'), ('SUBSCRIBE', 'SUBSCRIBE'), ('UNSUBSCRIBE', 'UNSUBSCRIBE'), ('ARCHIVE', 'ARCHIVE'), ('UPDATE', 'UPDATE')], default='CREATE', max_length=11)),
                ('andela_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AndelaUserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserEventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_event_action', models.CharField(choices=[('CREATE', 'CREATE'), ('DEACTIVATE', 'DEACTIVATE'), ('UPDATE', 'UPDATE'), ('ATTEND', 'ATTEND'), ('REJECT', 'REJECT')], default='CREATE', max_length=10)),
                ('andela_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AndelaUserProfile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
