# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180731_1127'),
        ('api', '0011_auto_20180726_0020'),
    ]

    operations = [
    ]
