# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usercategoryhistory_usereventhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategoryhistory',
            name='andela_user_profile',
        ),
        migrations.RemoveField(
            model_name='usercategoryhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usereventhistory',
            name='andela_user_profile',
        ),
        migrations.RemoveField(
            model_name='usereventhistory',
            name='event',
        ),
        migrations.DeleteModel(
            name='UserCategoryHistory',
        ),
        migrations.DeleteModel(
            name='UserEventHistory',
        ),
    ]
