# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-08 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180808_1431'),
        ('api', '0012_merge_20180806_1326'),
    ]

    operations = [
    ]
