# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_usercategoryhistory_usereventhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='status',
            field=models.CharField(choices=[('attending', 'attending'), ('declined', 'declined'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attend',
            unique_together=set([('user', 'event', 'status')]),
        ),
    ]
