# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-24 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180822_1409'),
        ('api', '0016_auto_20180814_1329'),
    ]

    operations = [
    ]
