# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180824_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
