# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-04 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180830_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
