# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180904_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendSet', to='api.Event'),
        ),
    ]
