# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_andelauserprofile_slack_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
