# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_event_event_id_in_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id_in_calendar',
            field=models.CharField(default='', max_length=150),
        ),
    ]
