# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171206_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attend',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='attend',
            unique_together=set([('user', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together=set([('follower', 'follower_category')]),
        ),
    ]
