export default {
  activeUser: {},
  event: {},
  events: [],
  subscribedEvents: [],
  redirectUrl: '',
  interest: {},
  interests: {},
  attendees: {},
  attendee: {},
  joinedCategories: {},
  socialClubs: {},
  socialClub: {},
  eventsSearchList: [],
  oauth: '',
  invite: {},
};
