export default {
  activeUser: {},
  event: {},
  events: {
    getEventsLoading: false,
  },
  subscribedEvents: [],
  redirectUrl: '',
  interest: {},
  interests: {},
  attendees: {},
  attendee: {},
  joinedCategories: {},
  socialClubs: {},
  socialClub: {},
  eventsSearchList: [],
  oauth: '',
  invite: {},
  slackChannels: {},
  ui: { subNavHidden: false },
  slackToken: true,
};
